import Head from "next/head";
import { useRouter } from "next/router";
import HreflangLinks from "@/components/SEO/HreflangLinks";

const owner = {
  name: "Agriturismo Segarelli",
  address: "Via Podere Segarelli n°6, 56045 Pomarance - Pisa (Italy)",
  email: "agriturismosegarelli@gmail.com",
  phone: "+39 347 7447180",
};

function Section({ title, children }) {
  return (
    <section className="flex flex-col gap-3">
      <h2 className="text-2xl lg:text-3xl text-primary">{title}</h2>
      <div className="flex flex-col gap-3 text-blu/80 leading-relaxed">
        {children}
      </div>
    </section>
  );
}

export default function PrivacyPolicy() {
  const { locale } = useRouter();
  const isEn = locale === "en";

  return (
    <>
      <Head>
        <title>
          {isEn
            ? "Privacy Policy | Agriturismo Segarelli"
            : "Privacy Policy | Agriturismo Segarelli"}
        </title>
        <meta
          name="description"
          content={
            isEn
              ? "Privacy information for Agriturismo Segarelli website users."
              : "Informativa privacy per gli utenti del sito Agriturismo Segarelli."
            }
        />
        <link
          rel="canonical"
          href={`https://www.agriturismosegarelli.it${isEn ? "/en" : ""}/privacy-policy`}
        />
        <HreflangLinks it="/privacy-policy" en="/en/privacy-policy" />
      </Head>

      <main className="px-4 lg:px-0 lg:w-[70%] mx-auto my-32 flex flex-col gap-10">
        <header className="flex flex-col gap-4">
          <h1 className="text-4xl lg:text-6xl text-primary">Privacy Policy</h1>
          <p className="text-blu/70">
            {isEn ? "Last updated: May 2026" : "Ultimo aggiornamento: maggio 2026"}
          </p>
        </header>

        {isEn ? (
          <>
            <Section title="Data Controller">
              <p>
                The Data Controller is {owner.name}, {owner.address}. Contact:
                {" "}{owner.email}, {owner.phone}.
              </p>
            </Section>

            <Section title="Data We Process">
              <p>
                We process data submitted through the contact and booking forms:
                name, surname or full name, email, phone, selected apartment,
                stay dates, number of guests, subject, message and notes.
              </p>
              <p>
                We may also process technical data generated by the use of the
                website, such as IP address, browser information, logs needed for
                security and operation, and cookie preferences stored locally on
                your device.
              </p>
            </Section>

            <Section title="Purposes and Legal Bases">
              <p>
                We use your data to reply to requests, manage booking enquiries,
                check availability, send confirmation emails, provide requested
                services and comply with legal obligations.
              </p>
              <p>
                The legal bases are pre-contractual measures requested by the
                user, fulfilment of legal obligations, legitimate interest in
                securing and operating the website, and consent where required
                for optional third-party services.
              </p>
            </Section>

            <Section title="Recipients and Third Parties">
              <p>
                Data may be processed by hosting providers, including Vercel,
                email and technical service providers. The website may use
                Google Analytics for statistics, Google Search Console for site
                ownership verification and search performance information,
                Google Maps embeds, Elfsight widgets, iCal availability sources,
                WhatsApp links, and links to social networks or review
                platforms. These third parties may process data according to
                their own policies when you interact with them or consent to
                their loading.
              </p>
              <p>
                Google Analytics is loaded only after consent to optional
                third-party services. Google Search Console verification is
                implemented through a static meta tag and does not, by itself,
                set cookies in the user's browser.
              </p>
            </Section>

            <Section title="Retention">
              <p>
                Requests received by email are kept for the time needed to manage
                the request and any related relationship, then for the period
                required by law or to protect rights. Technical logs are kept for
                limited periods compatible with security needs.
              </p>
            </Section>

            <Section title="Your Rights">
              <p>
                You may request access, rectification, erasure, restriction,
                portability and objection where applicable. You may also withdraw
                consent at any time, without affecting previous processing.
              </p>
              <p>
                To exercise your rights, contact {owner.email}. You may lodge a
                complaint with the Italian Data Protection Authority.
              </p>
            </Section>
          </>
        ) : (
          <>
            <Section title="Titolare del trattamento">
              <p>
                Il Titolare del trattamento e {owner.name}, {owner.address}.
                Contatti: {owner.email}, {owner.phone}.
              </p>
            </Section>

            <Section title="Dati trattati">
              <p>
                Trattiamo i dati inviati tramite i form di contatto e
                prenotazione: nome, cognome o nome completo, email, telefono,
                appartamento scelto, date del soggiorno, numero di ospiti,
                oggetto, messaggio e note.
              </p>
              <p>
                Possiamo trattare anche dati tecnici generati dall'uso del sito,
                come indirizzo IP, informazioni sul browser, log necessari per
                sicurezza e funzionamento, e preferenze cookie salvate localmente
                sul dispositivo.
              </p>
            </Section>

            <Section title="Finalita e basi giuridiche">
              <p>
                Usiamo i dati per rispondere alle richieste, gestire richieste di
                prenotazione, verificare disponibilita, inviare email di
                conferma, fornire i servizi richiesti e adempiere a obblighi di
                legge.
              </p>
              <p>
                Le basi giuridiche sono l'esecuzione di misure precontrattuali
                richieste dall'utente, l'adempimento di obblighi legali,
                l'interesse legittimo alla sicurezza e gestione del sito e, dove
                richiesto, il consenso per i servizi facoltativi di terze parti.
              </p>
            </Section>

            <Section title="Destinatari e terze parti">
              <p>
                I dati possono essere trattati da fornitori di hosting, incluso
                Vercel, fornitori tecnici e servizi email. Il sito puo usare
                Google Analytics per statistiche, Google Search Console per la
                verifica della proprieta del sito e le informazioni sulle
                prestazioni nella ricerca, incorporamenti Google Maps, widget
                Elfsight, fonti iCal per disponibilita, link WhatsApp e link a
                social network o piattaforme di recensioni. Queste terze parti
                possono trattare dati secondo le proprie informative quando
                interagisci con loro o acconsenti al caricamento.
              </p>
              <p>
                Google Analytics viene caricato solo dopo il consenso ai servizi
                facoltativi di terze parti. La verifica di Google Search Console
                e implementata tramite un meta tag statico e, da sola, non
                imposta cookie nel browser dell'utente.
              </p>
            </Section>

            <Section title="Conservazione">
              <p>
                Le richieste ricevute via email sono conservate per il tempo
                necessario a gestire la richiesta e l'eventuale rapporto, poi per
                i termini richiesti dalla legge o per tutelare diritti. I log
                tecnici sono conservati per periodi limitati compatibili con le
                esigenze di sicurezza.
              </p>
            </Section>

            <Section title="Diritti dell'interessato">
              <p>
                Puoi chiedere accesso, rettifica, cancellazione, limitazione,
                portabilita e opposizione nei casi previsti. Puoi revocare il
                consenso in qualsiasi momento, senza pregiudicare i trattamenti
                gia effettuati.
              </p>
              <p>
                Per esercitare i diritti scrivi a {owner.email}. Puoi proporre
                reclamo al Garante per la protezione dei dati personali.
              </p>
            </Section>
          </>
        )}
      </main>
    </>
  );
}
